### ISSUE TITLE
Track 2

### ISSUE THREAD

**Issue by zuenko** [yandexdataschool/IDAO-2019-muon-id#1]
Hello, please, may we have a python baseline for this task? 

Thanks!

**Comment by kazeevn** [comment]
Hello,

Thank you for the suggestion! We're working on an example Python solution. At the same time, I would expect it to be quite slow - thus sacrificing quality to adhere to the time limit.

**Comment by zuenko** [comment]
> Hello,
> 
> Thank you for the suggestion! We're working on an example Python solution. At the same time, I would expect it to be quite slow - thus sacrificing quality to adhere to the time limit.

Damn, that can be tough to do c++/c coding
